services:
  postgres:
    container_name: "order-postgres"
    image: "postgres:16-alpine"
    restart: "unless-stopped"
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: "order_user"
      POSTGRES_PASSWORD: "order_pass"
      POSTGRES_DB: "order_db"
    volumes:
      - "order_postgres_data:/var/lib/postgresql/data"
    networks:
      - "order_net"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  order_postgres_data: {}

networks:
  order_net: {}
